apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi-sample
  namespace: spark
spec:
  driver:
    coreLimit: 1200m
    cores: 1
    labels:
      version: 3.5.0
    memory: 512m
    serviceAccount: spark
    volumeMounts:
    - mountPath: /tmp
      name: test-volume
  executor:
    cores: 1
    instances: 1
    labels:
      version: 3.5.0
    memory: 512m
    volumeMounts:
    - mountPath: /tmp
      name: test-volume
  image: spark:3.5.0
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/examples/jars/spark-examples_2.12-3.5.0.jar
  mainClass: org.apache.spark.examples.SparkPi
  mode: cluster
  restartPolicy:
    type: Never
  sparkUIOptions:
    serviceLabels:
      test-label/v1: "true"
  sparkVersion: 3.5.0
  type: Scala
  volumes:
  - hostPath:
      path: /tmp
      type: Directory
    name: test-volume